//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
    public partial class Items 
    {

		public Items()		
		{
				
		}

		public readonly string DocTypeAlias = "Items";

		public static implicit operator string(Items doctype)
		{
			return "Items";
		}
	 
	}
}
