//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
    public partial class Link : Items
    {

		public Link(): base()		
		{
			this.InternalLink = new ContentProperty(){ Alias = "internalLink" };
				
		}

		[Obsolete("Use the implicit operator... Just remove the .DocTypeAlias")]
		new public readonly string DocTypeAlias = "Link";

		public static implicit operator string(Link doctype)
		{
			return "Link";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Content Picker</para>
		/// </summary>
		public ContentProperty InternalLink { get; private set; }
	}
}
