//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
    public partial class Location : Items
    {

		public Location(): base()		
		{
			this.Address = new StringProperty(){ Alias = "address" };
			this.GoogleMapsLink = new StringProperty(){ Alias = "googleMapsLink" };
				
		}

		[Obsolete("Use the implicit operator... Just remove the .DocTypeAlias")]
		new public readonly string DocTypeAlias = "Location";

		public static implicit operator string(Location doctype)
		{
			return "Location";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		/// </summary>
		public StringProperty Address { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		///		<para>Description: Indtast URL'en til adressen på google maps.</para>
		/// </summary>
		public StringProperty GoogleMapsLink { get; private set; }
	}
}
