//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
    public partial class LocationsRegion : Items
    {

		public LocationsRegion(): base()		
		{
				
		}

		[Obsolete("Use the implicit operator... Just remove the .DocTypeAlias")]
		new public readonly string DocTypeAlias = "LocationsRegion";

		public static implicit operator string(LocationsRegion doctype)
		{
			return "LocationsRegion";
		}
	 
	}
}
