//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
    public partial class Master 
    {

		public Master()		
		{
			this.SeoTitle = new StringProperty(){ Alias = "seoTitle" };
			this.SeoDescription = new StringProperty(){ Alias = "seoDescription" };
				
		}

		public readonly string DocTypeAlias = "Master";

		public static implicit operator string(Master doctype)
		{
			return "Master";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		///		<para>Description: Sidens primære titel. Bliver vist i browser tabben, samt kan blive brugt af google i søgeresultat listen.</para>
		/// </summary>
		public StringProperty SeoTitle { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		///		<para>Description: Skriv en kortfattet beskrivelse af sidens indhold på max 160 tegn. Hjælper ikke på ranking direkte, men kan blive brugt af google som tekst på søgeresultat siden. En god beskrivende tekst kan derfor stadig have relevans for antal besøgende, hvilket på sigt kan betyde højere ranking. Kan være et uddrag af selve sidens indhold.</para>
		/// </summary>
		public StringProperty SeoDescription { get; private set; }
	}
}
