

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
namespace WaterEvents.Classes.Cms
{
    public static class DocTypes
    {
        private static Master _Master;
        public static Master Master
        {
            get { return _Master ?? (_Master = new Master()); }
        }
        private static FrontPage _FrontPage;
        public static FrontPage FrontPage
        {
            get { return _FrontPage ?? (_FrontPage = new FrontPage()); }
        }
        private static Textpage _Textpage;
        public static Textpage Textpage
        {
            get { return _Textpage ?? (_Textpage = new Textpage()); }
        }
        private static Events _Events;
        public static Events Events
        {
            get { return _Events ?? (_Events = new Events()); }
        }
        private static Items _Items;
        public static Items Items
        {
            get { return _Items ?? (_Items = new Items()); }
        }
        private static Event _Event;
        public static Event Event
        {
            get { return _Event ?? (_Event = new Event()); }
        }
        private static Locations _Locations;
        public static Locations Locations
        {
            get { return _Locations ?? (_Locations = new Locations()); }
        }
        private static LocationsRegion _LocationsRegion;
        public static LocationsRegion LocationsRegion
        {
            get { return _LocationsRegion ?? (_LocationsRegion = new LocationsRegion()); }
        }
        private static Location _Location;
        public static Location Location
        {
            get { return _Location ?? (_Location = new Location()); }
        }
        private static Contactpage _Contactpage;
        public static Contactpage Contactpage
        {
            get { return _Contactpage ?? (_Contactpage = new Contactpage()); }
        }
    }
}

// Generated helper templates
// Generated items
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Contactpage.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Location.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\LocationsRegion.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Locations.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Event.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Items.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Events.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Textpage.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\FrontPage.cs
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Master.cs
