

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using APE.Umbraco;
namespace WaterEvents.Classes.Cms
{
	public static class Dictionary
	{
	}
}
// Generated helper templates
// Generated items
// WaterEvents\WaterEvents\WaterEvents\Classes\Cms\Umbraco.DictionaryKeys.cs
